stages:
  - lint
  - build
  - deploy
  - package


variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip


.build_cache:
  cache_rw:
    key: common-ci-cache
    paths:
      - .cache/pip/
    policy: pull-push
  cache_ro:
    key: common-ci-cache
    paths:
      - .cache/pip/
    policy: pull


# static source code analysis
lint:
  stage: lint
  image: europeanxfel/karabo-ci:miniconda-3lint
  script:
    - source ci/lint
  only:
    - branches
  except:
    - master

.unit_tests: &unit-tests-conda
  cache: !reference [ .build_cache, cache_rw ]
  stage: build
  script:
    - python ci/build.py extensions --clean --test
  only:
    - branches
  except:
    - master

.release_build: &release-build
  cache: !reference [ .build_cache, cache_rw ]
  stage: build
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: $CI_JOB_TOKEN
    UPLOAD_URL: $CI_API_V4_URL/projects/4562/packages/pypi
  script:
    - python ci/build.py extensions --clean --test --upload-wheel -P karaboExtensions/tags
    - python -m pip install twine --upgrade
    - cd dist
    - >
      for FILE in *.whl; do
        echo "Uploading to XFEL package registry: $FILE"
        # when an upload fails (400: bad request), it is because the package already exists
        # the '|| true' follows this command to ignore upload failures
        python3 -m twine upload --disable-progress-bar --skip-existing --repository-url $UPLOAD_URL $FILE || true
      done
  only:
    - /^(\d+\.)(\d+\.?)(\d+)$/
  except:
    - branches
    - schedules

.nightly_build_conda: &nightly-test-conda
  cache: !reference [ .build_cache, cache_rw ]
  stage: build
  script:
    - python ci/build.py extensions --clean --test --nightly
  only:
    - schedules

##### Release build #####

release build miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *release-build

##### Test build #####

unit tests miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *unit-tests-conda

unit tests miniconda-osx64:
  before_script:
    - ci/cleanup.sh
  tags:
    - macos
  <<: *unit-tests-conda

unit tests miniconda-win64:
  before_script:
    - ci/cleanup.cmd
  tags:
    - Win10
  <<: *unit-tests-conda

##### Nightly build ####

nightly test miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *nightly-test-conda


include:
  - project: karabo/gitlabci
    file: .mirror-device.yml
    ref: main
