.unit_tests: &unit-tests-conda
  script:
    - python ci/build.py extensions --clean --test
  only:
    - branches
  except:
    - master

.release_build: &release-build
  script:
    - python ci/build.py extensions --clean --test --upload-wheel -P karaboExtensions/tags
  only:
    - tags

.nightly_build_conda: &nightly-test-conda
  script:
    - python ci/build.py extensions --clean --test --nightly
  only:
    - schedules

##### Release build #####

release build miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *release-build

##### Test build #####

unit tests miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *unit-tests-conda

unit tests miniconda-osx64:
  before_script:
    - ci/cleanup.sh
  tags:
    - macos
  <<: *unit-tests-conda

unit tests miniconda-win64:
  before_script:
    - ci/cleanup.cmd
  tags:
    - Win10
  <<: *unit-tests-conda

##### Nightly build ####

nightly test miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *nightly-test-conda
