before_script:
  - source ci/prepare.sh "$CI_BUILD_NAME"

.test_build_template: &test_build
  script:
    - source ci/build.sh "$CI_BUILD_NAME"
    - source ci/test.sh "$CI_BUILD_NAME"
  only:
    - /^scantool.+$/
  except:
    - master

.release_build: &release-build
  script:
    - source ci/build.sh "$CI_BUILD_NAME"
    - source ci/upload.sh "$CI_BUILD_NAME"
  only:
    - /^(\d+\.)(\d+\.?)(\d+)$/
  except:
    - branches
    - schedules

##### Release build #####

release build miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *release-build

##### Test build #####

test:miniconda:
  image: europeanxfel/karabo-ci:miniconda-3
  <<: *test_build
