from ..const import (
    ACTUAL_STEP, CURRENT_INDEX, MOTOR_IDS, MOTOR_NAMES, MOTORS, SCAN_TYPE,
    SOURCE_IDS, SOURCE_NAMES, SOURCES, START_POSITIONS, STEPS, STOP_POSITIONS)

ASCAN_CONFIG = {
    SCAN_TYPE: "ascan",
    MOTORS: MOTOR_NAMES[:1],
    SOURCES: SOURCE_NAMES[:1],
    MOTOR_IDS: MOTOR_NAMES[:1],
    SOURCE_IDS: SOURCE_NAMES[:1],
    STEPS: [5],
    ACTUAL_STEP: 0,
    CURRENT_INDEX: [0],
    START_POSITIONS: [0],
    STOP_POSITIONS: [10]
}


A2SCAN_CONFIG = {
    SCAN_TYPE: "ascan",
    MOTORS: MOTOR_NAMES[:2],
    SOURCES: SOURCE_NAMES[:1],
    MOTOR_IDS: MOTOR_NAMES[:2],
    SOURCE_IDS: SOURCE_NAMES[:1],
    STEPS: [5],
    ACTUAL_STEP: 0,
    CURRENT_INDEX: [0],
    START_POSITIONS: [0, 5],
    STOP_POSITIONS: [10, 15]
}


MESH_CONFIG = {
    SCAN_TYPE: "mesh",
    MOTORS: MOTOR_NAMES[:2],
    SOURCES: SOURCE_NAMES[:1],
    MOTOR_IDS: MOTOR_NAMES[:2],
    SOURCE_IDS: SOURCE_NAMES[:1],
    STEPS: [5, 10],
    ACTUAL_STEP: 0,
    CURRENT_INDEX: [0, 0],
    START_POSITIONS: [10, 10],
    STOP_POSITIONS: [5, 20]
}


C2SCAN_CONFIG = {
    SCAN_TYPE: "cscan",
    MOTORS: MOTOR_NAMES[:2],
    SOURCES: SOURCE_NAMES[:1],
    MOTOR_IDS: MOTOR_NAMES[:2],
    SOURCE_IDS: SOURCE_NAMES[:1],
    STEPS: [5],
    ACTUAL_STEP: 0,
    CURRENT_INDEX: [0],
    START_POSITIONS: [0, 5],
    STOP_POSITIONS: [10, 15]
}
